<?php

namespace Scitap\BadgeBundle\Repository;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBadgesForUser($user)
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->join('b.badgeUnlocks', 'bu')
            ->where('bu.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult();
    }
}
