<?php

namespace AppBundle\Repository;

/**
 * InvitationCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
