oc_platforme:
    resource: "@OCPlatformeBundle/Resources/config/routing.yml"
    prefix:   /platforme
    resource:
app:
    resource: '@AppBundle/Controller/'
    type: annotation
login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }
login_check:
    path: /login_check
logout:
    path: /logout