<?php

namespace AppBundle\Repository;

/**
 * Option_Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Option_Repository extends \Doctrine\ORM\EntityRepository
{
}
