<?php

namespace AppBundle\Repository;

/**
 * PropertySearchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertySearchRepository extends \Doctrine\ORM\EntityRepository
{
}
