<?php

namespace OC\PlatformeBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdvert($advert_id, $limit)
    {
        $qb = $this->createQueryBuilder('app');
        $qb->innerJoin('app.advert', 'a')
            ->addSelect('a');
        $qb->orderBy('app.date', 'DESC');
        $qb->where('app.advert =:advert_id');
        $qb->setParameter('advert_id', $advert_id);
        $query = $qb->getQuery()->setMaxResults($limit);
        return $query->getResult();
    }

    /**
     *  LE NOMBRE D'APPLICATIONS SELON UN advert_id
     */
    public function getNbApplicationsByAdvert($advert_id)
    {
        $qb = $this->createQueryBuilder('app');
        $qb->select('count(app)');
        $qb->where('app.advert = :advert_id');
        $qb->setParameter('advert_id', $advert_id);
        $query = $qb->getQuery();
        $count = $query->getSingleScalarResult();
        return $count;
    }

    public function getApplicationsByAdvert($advert_id)
    {
        $qb = $this->createQueryBuilder('app')
            ->where('app.advert = :advert_id')
            ->setParameter('advert_id', $advert_id);
        $query = $qb->getQuery();
        return $query->getResult();
    }

    public function isFlood($ip, $seconds)
    {

    }
}
