imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        driver: pdo_mysql
        charset: UTF8
        host: localhost
        dbname: db_dev
        user: root
        password: root

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
